### ISSUE TITLE
Youtube style access to event? 

### ISSUE THREAD

**Issue by owena11** [JosephRedfern/FTS-Manager#7]
Suggestion: Add a primary key to the event that is a 32 char string, that then has routes to it such as `^/events/ [id] /action`.
Makes it easier to share events in the automated emails that are to follow, and as long as permissions are checked on the views its makes the links easily shareable.

**Comment by JosephRedfern** [comment]
A permalink type of thing? Should it be descriptive, or short?

**Comment by owena11** [comment]
Yeah that sort of thing. Descriptive more than short, with 36^32 possible strings not likely we will run out. (Does mathjax work in comments, no)

**Comment by JosephRedfern** [comment]
We could have descriptive permalink AND shortlink. Should be 62^4 (14776336) combinations of URL with 4 characters (A-Z, a-z, 0-9).

**Comment by JosephRedfern** [comment]
we have event ids and permalinks to events... they're not friendly but for now i'm going to close this as it's not really a priority!
